### ISSUE TITLE
GPTNeoX or Transformers support?

### ISSUE THREAD

**Issue by fblgit** [Glaciohound/LM-Infinite#1]
I'm trying to integrate LM-Infinite into GPTNeoX `pythia-dedup`. I managed to bring in the `lambda_attn` to work, but the rotary's implementation on the GPTNeoX is a bit different, and the heads is a `3 * hidden_size` to form QKV, and the other model has separated layers of `1 * hidden_size` that are independent Q/K/V. It managed to train, but during inference or evaluation (single batch) I got stuck on some shape mismatch.

I did managed to see the training benefit of `lambda_attn`, with a higher `it/s`. The GPU metrics are more smooth and steady on high throughput. The CPU exhibits also higher compute demand compared to traditional training and it doesn't appear to show any contention for the training. As a test, I did managed to train a larger context with the same hardware and at a higher performance, this works obviously.

Perhaps I was thinking wether having a folder or a separate repo with these `modeling_$model.py` that can be fit into transformers, would help to simplify the setup and adoption?

**Comment by Glaciohound** [comment]
Hello! It is a pleasure to see that this repo is of interest and help to you in some ways.

As for your suggestions, I am not sure if I get it. Are you suggesting that, instead of the current implementation of hijacking the `attn.forward` functions after loading models, we should implement a whole separate `modeling_$model.py` which contains the complete model and layer classes? I am afraid that this would increase the code overheads, especially when the `modeling_$model.py` files in the original Transformer library have newer versions.

Nevertheless, I strongly encourage you to play with the codes by yourself. If you do demonstrate that this code architecture has more benefits I am happy to adopt that! In recent weeks I might be too busy to maintain the repo myself (due to lots of deadlines) but will look forward to your updates.

**Comment by fblgit** [comment]
I think is simple to install a modified transformers library by `pip` from the repo and then load the pre-trained naturally.

I'm not entirely sure how to bring this model into my training loop. I make an instance of the model
```
GPT_J_Model(
  (model): GPTJForCausalLM(
    (transformer): GPTJModel(
      (wte): Embedding(50400, 4096)
      (drop): Dropout(p=0.0, inplace=False)
      (h): ModuleList(
        (0-27): 28 x GPTJBlock(
          (ln_1): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
          (attn): GPTJAttention(
            (attn_dropout): Dropout(p=0.0, inplace=False)
            (resid_dropout): Dropout(p=0.0, inplace=False)
            (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (out_proj): Linear(in_features=4096, out_features=4096, bias=False)
          )
          (mlp): GPTJMLP(
            (fc_in): Linear(in_features=4096, out_features=16384, bias=True)
            (fc_out): Linear(in_features=16384, out_features=4096, bias=True)
            (act): NewGELUActivation()
            (dropout): Dropout(p=0.0, inplace=False)
          )
        )
      )
      (ln_f): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
    )
    (lm_head): Linear(in_features=4096, out_features=50400, bias=True)
  )
)
```
Model is loaded in this way:
```
parameters_dict = {
    'truncation_side': {
        'value': 'right'
    },
    'use_lambda_mask': {
        'value': True
    },
    'local_branch': {
        'value': 2048
    },
    'global_branch': {
        'value': 100
    },
    'limit_distance': {
        'value': 2048
    },
    'triangle_offset': {
        'value': 0.0
    }
}

model = GPT_J_Model(base_model = 'EleutherAI/gpt-j-6b', parameters_dict['block_size']['value'], True, parameters_dict['truncation_side']['value'],
                            parameters_dict['use_lambda_mask']['value'], parameters_dict['local_branch']['value'], parameters_dict['global_branch']['value'],
                            parameters_dict['limit_distance']['value'], parameters_dict['triangle_offset']['value']
                            )
```
But when the trainer starts, it exits with the following error:
```
TypeError: _forward_unimplemented() got an unexpected keyword argument 'input_ids'
```

Any idea?

**Comment by fblgit** [comment]
It is easy to `pip` install from a repo the transformers library with the changes on it, also easier to port. But this way also works.
Just to note that inside GPT_J_Mode there is another `model` object with the model. Will keep testing and let you know, thanks.
