### ISSUE TITLE
推理代码是否支持batch推理？

### ISSUE THREAD

**Issue by 541wsy** [Glaciohound/LM-Infinite#12]
您好，
看到您代码中如果做dataloader，采用的是右侧padding。当使用batch推理的时候，这种右侧padding应该会对生成的token产生影响，并且，eval_generation和eval_downstream_task脚本似乎只支持batch size为1。请教一下是否可以支持batch推理呢？

**Comment by Glaciohound** [comment]
你好！llama模型本身设计时，不支持左padding。不过LM-Infinite通过代码改动的话，应该可以尝试支持。LM-Infinite的attention mask不是简单的masking，而是应该需要让attention看不到开头的padding对应的内容。
我最近时间有些紧张，可能需要过段时间来看看代码。如果你想自己试着实现我也很高兴和你沟通来提供一些帮助

**Comment by 541wsy** [comment]
好的，非常感谢你的回复😊

**Comment by 541wsy** [comment]
好的，非常感谢你的回复！😊

**Comment by Glaciohound** [comment]
好的！如果你自己有任何进展请踢我！
