### ISSUE TITLE
方法是否相当于ReRoPE+ Λ-shaped attention？

### ISSUE THREAD

**Issue by HT-NEKO** [Glaciohound/LM-Infinite#13]
您好，感谢您的工作！请问您的方法是否相当于ReRoPE+ Λ-shaped attention？感谢您的回复。

**Comment by Glaciohound** [comment]
你好！谢谢您的关注。是说的这篇工作吗：
https://github.com/bojone/rerope
那感觉确实应该是类似的

**Comment by HT-NEKO** [comment]
好的，十分感谢！
