### ISSUE TITLE
How to Inferance?

### ISSUE THREAD

**Issue by farrael004** [Glaciohound/LM-Infinite#2]
The documentation does not make it clear how to perform inference using the lambda attention.

**Comment by Glaciohound** [comment]
Hello!

If you are questioning about generation, this section probably helps: https://github.com/Glaciohound/LM-Infinite#generation.

The function to be called is `model.generate`, which is implemented in [`models.model_base.Model_Base.generate()`](https://github.com/Glaciohound/LM-Infinite/blob/main/models/model_base.py#L71-L86), which is worth checking  out ^_^.

Best
