### ISSUE TITLE
limited_distance_forward() got an unexpected keyword argument 'padding_mask'

### ISSUE THREAD

**Issue by dittops** [Glaciohound/LM-Infinite#3]
I'm trying to run the eval script. 

```python
PYTHONPATH=. deepspeed --include localhost:$CUDA_VISIBLE_DEVICES --master_port $MASTER_PORT scripts/eval_downstream_tasks.py     --deepspeed_config configs/zero3_efficient_config.json     --model meta-llama/Llama-2-7b-hf --tokenizer_path meta-llama/Llama-2-7b-hf     --use_lambda_attention --local_branch 4096 --global_branch 100 --limit_distance 4096     --dataset passkey_retrieval --dataset_dir ${PASSKEY_DATA} --dataset_group ${MAX_LENGTH}     --max_generation_length 10 --evaluate_metrics     --log_dir $LOG_DIR/$TRIAL
```
<img width="711" alt="image" src="https://github.com/Glaciohound/LM-Infinite/assets/12937285/e4ecfdf0-a8ff-43ad-a4f6-0330bc0fb0c7">

**Comment by Glaciohound** [comment]
Hi, this is due to recent updates in `modeling_llama.py` in Huggingface Transformers. We updated the codes (and ignored padding mask for now, as it is newly introduced, not frequently used and hard to be compatible).

Feel free to pull the newest codes. ^_^
