### ISSUE TITLE
Should the llama model be fine-tuned?

### ISSUE THREAD

**Issue by yinwangsong** [Glaciohound/LM-Infinite#5]
Hello! I am a rookie to LLMs and I want to reproduce your nice work with the llama model (not the llama2).
Should I fine-tune the llama model on ARXIV or OpenWebText2 before evaluating it?
From my comprehension these two datasets are both the pre-training dataset of llama, so maybe the raw weights of llama model just work?
Thank you so much for your reply~

**Comment by Glaciohound** [comment]
Hello! Thank you for your interest in our work!

LM-Infinite is a plug-and-play extension to LLMs, so LLMs do not need to be finetuned to work with LM-Infinite, no matter whether the dataset was included in pre-training or not.
